### PR TITLE
service-identity v21.1.0 (with package rename)

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR implements the version update from #2 and also renames the main conda package to match the upstream metadata change from https://github.com/pyca/service-identity/commit/4ebe1546204829878317b46334d012d6f474075d.

The recipe layout was heavily influenced by the same sort of system used by [setuptools-scm-feedstock](https://github.com/conda-forge/setuptools_scm-feedstock/tree/cc9e4dad1ee2f3bc7b2dec4dd5639b28ec76ba54/recipe/).

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jonashaag** [comment]
@conda-forge-admin serenader

**Comment by jonashaag** [comment]
@conda-forge-admin rerender

**Comment by jonashaag** [comment]
@Conda-forge-admin restart CI

**Comment by jonashaag** [comment]
@duncanmmacleod ready to go?

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod ready to go?

I think so, if the CI passes I'm happy.

**Comment by jonashaag** [comment]
@isuruf

**Comment by jonashaag** [comment]
ping @isuruf

**Pull request merged**
